"""
Unit tests for scripts/analyze_common_setup.py

Tests common setup requirement identification across test cases.
"""

import json

from scripts.analyze_common_setup import analyze_common_setup
from tests.constants import (
    INDEX_MD_TABLE_FORMAT,
    TC_WITH_SHARED_PRECONDITIONS_1,
    TC_WITH_SHARED_PRECONDITIONS_2,
    TC_WITH_SHARED_PRECONDITIONS_3,
)


class TestAnalyzeCommonSetup:
    """Test analyze_common_setup function."""

    def test_finds_common_preconditions_with_table_format_index(self, tmp_path):
        """
        Should find common preconditions when INDEX.md uses table format.

        This is the ACTUAL format generated by test-plan-create-cases skill.
        """
        tc_dir = tmp_path / "test_cases"
        tc_dir.mkdir()

        # Create INDEX.md with table format (actual format from real test plans)
        (tc_dir / "INDEX.md").write_text(INDEX_MD_TABLE_FORMAT)

        # Create test cases with overlapping preconditions
        # TC-PIPE-001 and TC-PIPE-003 share: "Upgrade matrix configured with supported paths"
        # TC-PIPE-001 and TC-PIPE-002 share: "CI pipeline infrastructure connected to release system"
        (tc_dir / "TC-PIPE-001.md").write_text(TC_WITH_SHARED_PRECONDITIONS_1)
        (tc_dir / "TC-PIPE-002.md").write_text(TC_WITH_SHARED_PRECONDITIONS_2)
        (tc_dir / "TC-PIPE-003.md").write_text(TC_WITH_SHARED_PRECONDITIONS_3)

        result_json = analyze_common_setup(str(tmp_path))
        result = json.loads(result_json)

        assert isinstance(result, list), "Result should be a list"
        assert len(result) == 2, f"Should find 2 common preconditions, got {len(result)}: {result}"

        requirement_texts = [req["requirement"] for req in result]

        assert "Upgrade matrix configured with supported paths" in requirement_texts
        assert "CI pipeline infrastructure connected to release system" in requirement_texts

        for req in result:
            assert req["count"] == 2
            assert len(req["used_by_tcs"]) == 2

    def test_returns_empty_when_no_common_preconditions(self, tmp_path):
        """Should return empty list when TCs have no overlapping preconditions."""
        tc_dir = tmp_path / "test_cases"
        tc_dir.mkdir()

        # Create INDEX.md with table format
        (tc_dir / "INDEX.md").write_text("""# Test Case Index

| Test Case | Title | Priority |
|-----------|-------|----------|
| [TC-API-001](TC-API-001.md) | Test API endpoint | P0 |
| [TC-UI-001](TC-UI-001.md) | Test UI dashboard | P0 |
""")

        # Create TCs with unique preconditions (no overlap)
        (tc_dir / "TC-API-001.md").write_text("""---
test_case_id: TC-API-001
priority: P0
---
# TC-API-001: Test API endpoint

**Objective**: Verify API endpoint returns correct response

**Preconditions**:
- API server running
- Database accessible

**Test Steps**:
1. Call API

**Expected Results**:
- Returns 200
""")

        (tc_dir / "TC-UI-001.md").write_text("""---
test_case_id: TC-UI-001
priority: P0
---
# TC-UI-001: Test UI dashboard

**Objective**: Verify dashboard loads successfully

**Preconditions**:
- Dashboard accessible
- User logged in

**Test Steps**:
1. Open dashboard

**Expected Results**:
- Dashboard loads
""")

        result_json = analyze_common_setup(str(tmp_path))
        result = json.loads(result_json)

        assert result == []

    def test_returns_empty_when_index_missing(self, tmp_path):
        """Should return empty list when INDEX.md doesn't exist."""
        tc_dir = tmp_path / "test_cases"
        tc_dir.mkdir()

        # No INDEX.md created
        result_json = analyze_common_setup(str(tmp_path))
        result = json.loads(result_json)

        assert result == []
